eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8763

spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: false
    test-while-idle: true
    test-on-return: false
    validation-query: SELECT 1